name: My workflow

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main

defaults:
  run:
    working-directory: tt
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get branch name
        run: echo ${{ github.ref_name }}
